### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by royfraction**
Here are the changes and optimizations made to the original script:

Refactoring Methods: The handle_DATA method has been refactored to move the email content extraction logic into its own method (extract_plain_text). This improves readability and separates concerns.

Use asyncio.create_task: Instead of directly running the server using controller.start(), we use asyncio.create_task to run the server in the background as a coroutine. This allows the script to continue executing other tasks and makes the server more responsive.

Separate start_server Coroutine: The server setup logic is now placed inside the start_server coroutine, which is responsible for starting the SMTP server. This separation of concerns improves code organization.

Main Function and asyncio.run(): The script's main entry point is wrapped in a if __name__ == '__main__': block. The main coroutine is used with asyncio.run() to start the event loop and run the server.

Bind to All Interfaces: In the Controller setup, the hostname is set to '0.0.0.0' to bind the server to all available network interfaces. This allows the server to accept connections from any IP address, making it more flexible.

These changes enhance the efficiency and organization of the script while maintaining its functionality as a simple SMTP server for testing purposes. Keep in mind that this script is still meant for local development and may not cover all production-level requirements for a robust SMTP server.

Here are the user-friendly enhancements made:

Improved Messages: The script provides clearer and more informative messages throughout its execution. Users are guided on what to expect and how to interact with the server.

Rejected Address Message: The script prints a message when an email is rejected due to the recipient address not ending with @kianbrose.com.

Server Start Message: The script now prints messages to indicate when the SMTP server has started successfully and is ready to receive emails.

Server Stop Message: When the server is stopped with Ctrl+C, a message is displayed to inform the user that the server has been stopped.

These enhancements should make the script more user-friendly and provide better guidance for users interacting with the SMTP server.

In this version, I've added additional prompts and explanations to guide users through the process of using the SMTP server for local testing and development. The script provides a more comprehensive introduction and step-by-step instructions to make it as user-friendly as possible.

### CODE REVIEW

**Comment by KianBrose** [comment]
kind of reads like this was made with chatgpt lmfao
but okay

**Comment by royfraction** [comment]
It was

**Comment by terrified9** [comment]
this doesn't work for me, it just instantly closes (run_forever missing?)

**Comment by KianBrose** [comment]
> this doesn't work for me, it just instantly closes (run_forever missing?)

What was the error? Does the previous version before the PR work?

**Comment by terrified9** [comment]
> > this doesn't work for me, it just instantly closes (run_forever missing?)
> 
> What was the error? Does the previous version before the PR work?

Your original version (from 3 months ago works). This one doesn't have an error, it just doesn't keep running.

**Comment by terrified9** [comment]
Maybe it's my ubuntu issue but the first version works so idk

**Comment by KianBrose** [comment]
> > > this doesn't work for me, it just instantly closes (run_forever missing?)
> > 
> > 
> > What was the error? Does the previous version before the PR work?
> 
> Your original version (from 3 months ago works). This one doesn't have an error, it just doesn't keep running.

I'll revert it

**Pull request merged**
